name: kubecustom

channels:
  - conda-forge

dependencies:
  - python
  - pip
  - numpy
  - kubernetes
  - pyyaml
  - sphinx>2.1
  - docutils>=0.17
  - InquirerPy
  - pre-commit
  - black
  - sphinx-design
  - sphinx-copybutton
  - pydata-sphinx-theme
  - nbsphinx
